# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20180707_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='power_station',
            field=models.CharField(choices=[('Hisar', 'Hisar'), ('Panipat', 'Panipat'), ('Yamuna Nagar', 'Yamuna Nagar'), ('Panchkula', 'Panchkula')], default='', max_length=200),
        ),
    ]
