# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_user_power_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('MP&GS', 'MP&GS'), ('O&M1', 'O&M1'), ('O&M2', 'QAO&M2'), ('M&T', 'M&T'), ('MM&Store', 'MM&Store'), ('Civil', 'Civil')], max_length=200),
        ),
    ]
