# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-19 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20180707_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('MP&GS', 'MP&GS'), ('O&M1', 'O&M1'), ('O&M2', 'QAO&M2'), ('M&T', 'M&T'), ('MM&Store', 'MM&Store'), ('Civil', 'Civil')], max_length=200, null=True),
        ),
    ]
