# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20180819_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='noted_to',
            new_name='noted_by',
        ),
    ]
