# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 19:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20181223_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='noted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_notedto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='noted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_notedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
