# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_auto_20181223_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_image',
            field=models.ImageField(default='leaves_images/None/no-img.jpg', upload_to='leaves_images/'),
        ),
    ]
