# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-23 19:57
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_leave_leave_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
